services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" 
      - "9001:9001" # MinIO Console
    volumes:
      - minio_data:/data
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes: ["pgdata2:/var/lib/postgresql/data"]
  adminer:
    image: adminer
    ports: ["8080:8080"]
volumes:
  pgdata2:
  minio_data: