// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_add_procedure_cats__cat_id__procedures_post
 */
export type BodyAddProcedureCatsCatIdProceduresPost = {
    /**
     * Payload
     */
    payload: string;
    /**
     * File
     */
    file?: Blob | File | null;
};

/**
 * Body_create_cat_cats_post
 */
export type BodyCreateCatCatsPost = {
    /**
     * Payload
     */
    payload: string;
    /**
     * Primary Image
     */
    primary_image?: Blob | File | null;
};

/**
 * Body_update_cat_cats__cat_id__patch
 */
export type BodyUpdateCatCatsCatIdPatch = {
    /**
     * Payload
     */
    payload: string;
    /**
     * Primary Image
     */
    primary_image?: Blob | File | null;
};

/**
 * CatRead
 */
export type CatRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Sex
     */
    sex: 'male' | 'female' | 'unknown' | null;
    /**
     * Chip Number
     */
    chip_number: string | null;
    /**
     * Status
     */
    status: 'ACTIVE' | 'FOSTER' | 'ADOPTED' | 'ARCHIVED' | 'MISSING' | 'RESERVED';
    manager?: ManagerRef | null;
    foster_home?: FosterHomeRef | null;
    colony?: ColonyRef | null;
    /**
     * Intake Date
     */
    intake_date?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    /**
     * Foster End Date
     */
    foster_end_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Neutered
     */
    is_neutered?: boolean | null;
    /**
     * Primary Photo Object
     */
    primary_photo_object?: string | null;
};

/**
 * ColonyCreate
 */
export type ColonyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Cat Ids
     */
    cat_ids?: Array<number> | null;
};

/**
 * ColonyRead
 */
export type ColonyRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Cats
     */
    cats: Array<CatRead>;
};

/**
 * ColonyRef
 */
export type ColonyRef = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * FosterHomeCreate
 */
export type FosterHomeCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Comments
     */
    comments?: string | null;
};

/**
 * FosterHomeRead
 */
export type FosterHomeRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Comments
     */
    comments?: string | null;
};

/**
 * FosterHomeRef
 */
export type FosterHomeRef = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * FosterHomeUpdate
 */
export type FosterHomeUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Comments
     */
    comments?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    [key: string]: unknown;
};

/**
 * ManagerRef
 */
export type ManagerRef = {
    /**
     * Id
     */
    id: number;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ProcedureRead
 */
export type ProcedureRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Cat Id
     */
    cat_id: number;
    /**
     * Type
     */
    type: 'DEWORMER' | 'SPOT_ON' | 'VACCINE';
    /**
     * Is Repeat
     */
    is_repeat: boolean;
    /**
     * At Date
     */
    at_date: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * File Object
     */
    file_object?: string | null;
    /**
     * Payment
     */
    payment?: number | null;
};

/**
 * RoleRead
 */
export type RoleRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Permissions
     */
    permissions: Array<string>;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Cat Id
     */
    cat_id: number;
    /**
     * Type
     */
    type: 'VET_VISIT' | 'MEDICATION' | 'PERSONAL';
    /**
     * Due Date
     */
    due_date: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Cat Id
     */
    cat_id: number;
    /**
     * Type
     */
    type: 'VET_VISIT' | 'MEDICATION' | 'PERSONAL';
    /**
     * Due Date
     */
    due_date: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Role Id
     */
    role_id: number | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Display Name
     */
    display_name: string;
    role: RoleRead;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Email
     */
    email: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Role Id
     */
    role_id: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * CatCreate
 */
export type CatCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Sex
     */
    sex?: 'male' | 'female' | 'unknown' | null;
    /**
     * Chip Number
     */
    chip_number?: string | null;
    /**
     * Status
     */
    status?: 'ACTIVE' | 'FOSTER' | 'ADOPTED' | 'ARCHIVED' | 'MISSING' | 'RESERVED';
    /**
     * Manager Id
     */
    manager_id?: number | null;
    /**
     * Foster Home Id
     */
    foster_home_id?: number | null;
    /**
     * Colony Id
     */
    colony_id?: number | null;
    /**
     * Intake Date
     */
    intake_date?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    /**
     * Foster End Date
     */
    foster_end_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Neutered
     */
    is_neutered?: boolean | null;
};

/**
 * CatUpdate
 */
export type CatUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Sex
     */
    sex?: 'male' | 'female' | 'unknown' | null;
    /**
     * Chip Number
     */
    chip_number?: string | null;
    /**
     * Status
     */
    status?: 'ACTIVE' | 'FOSTER' | 'ADOPTED' | 'ARCHIVED' | 'MISSING' | 'RESERVED' | null;
    /**
     * Manager Id
     */
    manager_id?: number | null;
    /**
     * Foster Home Id
     */
    foster_home_id?: number | null;
    /**
     * Colony Id
     */
    colony_id?: number | null;
    /**
     * Intake Date
     */
    intake_date?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    /**
     * Foster End Date
     */
    foster_end_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Neutered
     */
    is_neutered?: boolean | null;
};

/**
 * Permissions
 */
export type Permissions = {
    /**
     * cat:create
     */
    CAT_CREATE: 'cat:create';
    /**
     * cat:read
     */
    CAT_READ: 'cat:read';
    /**
     * cat:update
     */
    CAT_UPDATE: 'cat:update';
    /**
     * cat:delete
     */
    CAT_DELETE: 'cat:delete';
    /**
     * colony:add
     */
    COLONY_ADD: 'colony:add';
    /**
     * colony:view
     */
    COLONY_VIEW: 'colony:view';
    /**
     * colony:edit
     */
    COLONY_EDIT: 'colony:edit';
    /**
     * colony:remove
     */
    COLONY_REMOVE: 'colony:remove';
    /**
     * user:create
     */
    USER_CREATE: 'user:create';
    /**
     * user:read
     */
    USER_READ: 'user:read';
    /**
     * user:update
     */
    USER_UPDATE: 'user:update';
    /**
     * user:delete
     */
    USER_DELETE: 'user:delete';
    /**
     * foster:create
     */
    FOSTER_CREATE: 'foster:create';
    /**
     * foster:read
     */
    FOSTER_READ: 'foster:read';
    /**
     * foster:update
     */
    FOSTER_UPDATE: 'foster:update';
    /**
     * foster:delete
     */
    FOSTER_DELETE: 'foster:delete';
    /**
     * procedures:create
     */
    PROCEDURES_CREATE: 'procedures:create';
    /**
     * procedures:read
     */
    PROCEDURES_READ: 'procedures:read';
    /**
     * procedures:update
     */
    PROCEDURES_UPDATE: 'procedures:update';
    /**
     * procedures:delete
     */
    PROCEDURES_DELETE: 'procedures:delete';
    /**
     * task:create
     */
    TASK_CREATE: 'task:create';
    /**
     * task:read
     */
    TASK_READ: 'task:read';
    /**
     * task:update
     */
    TASK_UPDATE: 'task:update';
    /**
     * task:delete
     */
    TASK_DELETE: 'task:delete';
};

/**
 * Roles
 */
export type Roles = {
    /**
     * ADMIN
     */
    ADMIN: 'ADMIN';
    /**
     * MANAGER
     */
    MANAGER: 'MANAGER';
    /**
     * SOCIAL_WORKER
     */
    SOCIAL_WORKER: 'SOCIAL_WORKER';
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginPostError = LoginLoginPostErrors[keyof LoginLoginPostErrors];

export type LoginLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginLoginPostResponse = LoginLoginPostResponses[keyof LoginLoginPostResponses];

export type CreateUserFullUsersFullCreatePostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/full-create';
};

export type CreateUserFullUsersFullCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserFullUsersFullCreatePostError = CreateUserFullUsersFullCreatePostErrors[keyof CreateUserFullUsersFullCreatePostErrors];

export type CreateUserFullUsersFullCreatePostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserFullUsersFullCreatePostResponse = CreateUserFullUsersFullCreatePostResponses[keyof CreateUserFullUsersFullCreatePostResponses];

export type GetAllRolesRolesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles';
};

export type GetAllRolesRolesGetResponses = {
    /**
     * Response Get All Roles Roles Get
     *
     * Successful Response
     */
    201: Array<RoleRead>;
};

export type GetAllRolesRolesGetResponse = GetAllRolesRolesGetResponses[keyof GetAllRolesRolesGetResponses];

export type GetAllPermissionsPermissionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/permissions';
};

export type GetAllPermissionsPermissionsGetResponses = {
    /**
     * Response Get All Permissions Permissions Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetAllPermissionsPermissionsGetResponse = GetAllPermissionsPermissionsGetResponses[keyof GetAllPermissionsPermissionsGetResponses];

export type ListManagersManagersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/managers';
};

export type ListManagersManagersGetResponses = {
    /**
     * Response List Managers Managers Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type ListManagersManagersGetResponse = ListManagersManagersGetResponses[keyof ListManagersManagersGetResponses];

export type ListUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersUsersGetResponses = {
    /**
     * Response List Users Users Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type ListUsersUsersGetResponse = ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EditUserUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type EditUserUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditUserUsersUserIdPatchError = EditUserUsersUserIdPatchErrors[keyof EditUserUsersUserIdPatchErrors];

export type EditUserUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type EditUserUsersUserIdPatchResponse = EditUserUsersUserIdPatchResponses[keyof EditUserUsersUserIdPatchResponses];

export type ListCatsCatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cats';
};

export type ListCatsCatsGetResponses = {
    /**
     * Response List Cats Cats Get
     *
     * Successful Response
     */
    200: Array<CatRead>;
};

export type ListCatsCatsGetResponse = ListCatsCatsGetResponses[keyof ListCatsCatsGetResponses];

export type CreateCatCatsPostData = {
    body: BodyCreateCatCatsPost;
    path?: never;
    query?: never;
    url: '/cats';
};

export type CreateCatCatsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCatCatsPostError = CreateCatCatsPostErrors[keyof CreateCatCatsPostErrors];

export type CreateCatCatsPostResponses = {
    /**
     * Successful Response
     */
    201: CatRead;
};

export type CreateCatCatsPostResponse = CreateCatCatsPostResponses[keyof CreateCatCatsPostResponses];

export type DeleteCatCatsCatIdDeleteData = {
    body?: never;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}';
};

export type DeleteCatCatsCatIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCatCatsCatIdDeleteError = DeleteCatCatsCatIdDeleteErrors[keyof DeleteCatCatsCatIdDeleteErrors];

export type DeleteCatCatsCatIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCatCatsCatIdDeleteResponse = DeleteCatCatsCatIdDeleteResponses[keyof DeleteCatCatsCatIdDeleteResponses];

export type GetCatCatsCatIdGetData = {
    body?: never;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}';
};

export type GetCatCatsCatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCatCatsCatIdGetError = GetCatCatsCatIdGetErrors[keyof GetCatCatsCatIdGetErrors];

export type GetCatCatsCatIdGetResponses = {
    /**
     * Successful Response
     */
    200: CatRead;
};

export type GetCatCatsCatIdGetResponse = GetCatCatsCatIdGetResponses[keyof GetCatCatsCatIdGetResponses];

export type UpdateCatCatsCatIdPatchData = {
    body: BodyUpdateCatCatsCatIdPatch;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}';
};

export type UpdateCatCatsCatIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCatCatsCatIdPatchError = UpdateCatCatsCatIdPatchErrors[keyof UpdateCatCatsCatIdPatchErrors];

export type UpdateCatCatsCatIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CatRead;
};

export type UpdateCatCatsCatIdPatchResponse = UpdateCatCatsCatIdPatchResponses[keyof UpdateCatCatsCatIdPatchResponses];

export type GetAllColoniesColoniesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/colonies';
};

export type GetAllColoniesColoniesGetResponses = {
    /**
     * Response Get All Colonies Colonies Get
     *
     * Successful Response
     */
    200: Array<ColonyRead>;
};

export type GetAllColoniesColoniesGetResponse = GetAllColoniesColoniesGetResponses[keyof GetAllColoniesColoniesGetResponses];

export type CreateColonyColoniesPostData = {
    body: ColonyCreate;
    path?: never;
    query?: never;
    url: '/colonies';
};

export type CreateColonyColoniesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateColonyColoniesPostError = CreateColonyColoniesPostErrors[keyof CreateColonyColoniesPostErrors];

export type CreateColonyColoniesPostResponses = {
    /**
     * Successful Response
     */
    201: ColonyRead;
};

export type CreateColonyColoniesPostResponse = CreateColonyColoniesPostResponses[keyof CreateColonyColoniesPostResponses];

export type GetColonyColoniesColonyIdGetData = {
    body?: never;
    path: {
        /**
         * Colony Id
         */
        colony_id: number;
    };
    query?: never;
    url: '/colonies/{colony_id}';
};

export type GetColonyColoniesColonyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetColonyColoniesColonyIdGetError = GetColonyColoniesColonyIdGetErrors[keyof GetColonyColoniesColonyIdGetErrors];

export type GetColonyColoniesColonyIdGetResponses = {
    /**
     * Successful Response
     */
    201: ColonyRead;
};

export type GetColonyColoniesColonyIdGetResponse = GetColonyColoniesColonyIdGetResponses[keyof GetColonyColoniesColonyIdGetResponses];

export type ListFosterHomesFosterHomesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/foster-homes';
};

export type ListFosterHomesFosterHomesGetResponses = {
    /**
     * Response List Foster Homes Foster Homes Get
     *
     * Successful Response
     */
    200: Array<FosterHomeRead>;
};

export type ListFosterHomesFosterHomesGetResponse = ListFosterHomesFosterHomesGetResponses[keyof ListFosterHomesFosterHomesGetResponses];

export type CreateFosterHomeFosterHomesPostData = {
    body: FosterHomeCreate;
    path?: never;
    query?: never;
    url: '/foster-homes';
};

export type CreateFosterHomeFosterHomesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFosterHomeFosterHomesPostError = CreateFosterHomeFosterHomesPostErrors[keyof CreateFosterHomeFosterHomesPostErrors];

export type CreateFosterHomeFosterHomesPostResponses = {
    /**
     * Successful Response
     */
    201: FosterHomeRead;
};

export type CreateFosterHomeFosterHomesPostResponse = CreateFosterHomeFosterHomesPostResponses[keyof CreateFosterHomeFosterHomesPostResponses];

export type UpdateCatFosterHomesHomeIdPatchData = {
    body: FosterHomeUpdate;
    path: {
        /**
         * Home Id
         */
        home_id: number;
    };
    query?: never;
    url: '/foster-homes/{home_id}';
};

export type UpdateCatFosterHomesHomeIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCatFosterHomesHomeIdPatchError = UpdateCatFosterHomesHomeIdPatchErrors[keyof UpdateCatFosterHomesHomeIdPatchErrors];

export type UpdateCatFosterHomesHomeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: FosterHomeRead;
};

export type UpdateCatFosterHomesHomeIdPatchResponse = UpdateCatFosterHomesHomeIdPatchResponses[keyof UpdateCatFosterHomesHomeIdPatchResponses];

export type GetImageImageObjectNameGetData = {
    body?: never;
    path: {
        /**
         * Object Name
         */
        object_name: string;
    };
    query?: never;
    url: '/image/{object_name}';
};

export type GetImageImageObjectNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageImageObjectNameGetError = GetImageImageObjectNameGetErrors[keyof GetImageImageObjectNameGetErrors];

export type GetImageImageObjectNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListProceduresCatsCatIdProceduresGetData = {
    body?: never;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}/procedures';
};

export type ListProceduresCatsCatIdProceduresGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProceduresCatsCatIdProceduresGetError = ListProceduresCatsCatIdProceduresGetErrors[keyof ListProceduresCatsCatIdProceduresGetErrors];

export type ListProceduresCatsCatIdProceduresGetResponses = {
    /**
     * Response List Procedures Cats  Cat Id  Procedures Get
     *
     * Successful Response
     */
    200: Array<ProcedureRead>;
};

export type ListProceduresCatsCatIdProceduresGetResponse = ListProceduresCatsCatIdProceduresGetResponses[keyof ListProceduresCatsCatIdProceduresGetResponses];

export type AddProcedureCatsCatIdProceduresPostData = {
    body: BodyAddProcedureCatsCatIdProceduresPost;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}/procedures';
};

export type AddProcedureCatsCatIdProceduresPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddProcedureCatsCatIdProceduresPostError = AddProcedureCatsCatIdProceduresPostErrors[keyof AddProcedureCatsCatIdProceduresPostErrors];

export type AddProcedureCatsCatIdProceduresPostResponses = {
    /**
     * Successful Response
     */
    201: ProcedureRead;
};

export type AddProcedureCatsCatIdProceduresPostResponse = AddProcedureCatsCatIdProceduresPostResponses[keyof AddProcedureCatsCatIdProceduresPostResponses];

export type ListTasksTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type ListTasksTasksGetResponses = {
    /**
     * Response List Tasks Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ListTasksTasksGetResponse = ListTasksTasksGetResponses[keyof ListTasksTasksGetResponses];

export type CreateTaskTasksPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type CreateTaskTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTasksPostError = CreateTaskTasksPostErrors[keyof CreateTaskTasksPostErrors];

export type CreateTaskTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type CreateTaskTasksPostResponse = CreateTaskTasksPostResponses[keyof CreateTaskTasksPostResponses];

export type ListTasksForCatCatsCatIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Cat Id
         */
        cat_id: number;
    };
    query?: never;
    url: '/cats/{cat_id}/tasks';
};

export type ListTasksForCatCatsCatIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksForCatCatsCatIdTasksGetError = ListTasksForCatCatsCatIdTasksGetErrors[keyof ListTasksForCatCatsCatIdTasksGetErrors];

export type ListTasksForCatCatsCatIdTasksGetResponses = {
    /**
     * Response List Tasks For Cat Cats  Cat Id  Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ListTasksForCatCatsCatIdTasksGetResponse = ListTasksForCatCatsCatIdTasksGetResponses[keyof ListTasksForCatCatsCatIdTasksGetResponses];
